import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const USERNAME = 'sixtdreanight'
const SYNCED_FILE = join(import.meta.dirname, '..', 'src', 'data', 'projects-synced.ts')
const GITHUB_TOKEN = process.env.GITHUB_TOKEN

if (!GITHUB_TOKEN) {
  console.error('GITHUB_TOKEN not set')
  process.exit(1)
}

const QUERY = `
query {
  viewer {
    repositories(first: 50, ownerAffiliations: OWNER, orderBy: {field: UPDATED_AT, direction: DESC}) {
      nodes {
        name
        description
        url
        owner { login }
        languages(first: 3, orderBy: {field: SIZE, direction: DESC}) {
          nodes { name }
        }
        object(expression: "HEAD:README.md") {
          ... on Blob {
            text
          }
        }
      }
    }
  }
}`

function guessCategory(repo) {
  if (repo.languages?.nodes?.length) {
    const primary = repo.languages.nodes[0].name.toLowerCase()
    if (['swift', 'kotlin', 'java', 'dart'].includes(primary)) return 'mobile'
    if (['c++', 'c#', 'rust', 'go'].includes(primary) || primary.includes('cpp')) return 'desktop'
  }
  return 'web'
}

function escapeStr(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')
}

function toProjectEntry(repo) {
  const title = escapeStr(repo.name)
  const desc = escapeStr(repo.description || `${repo.name} - GitHub repository`)
  const image = `https://opengraph.githubassets.com/1/${repo.owner.login}/${repo.name}`
  const link = repo.url
  const category = guessCategory(repo)
  return `  {
    id: '${repo.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}',
    title: '${title}',
    description: '${desc}',
    image: '${image}',
    category: '${category}',
    techStack: [],
    status: 'in-progress',
    sourceCode: '${link}',
    startDate: '',
    tags: [],
  }`
}

async function main() {
  console.log('Fetching repos...')
  const res = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      Authorization: `bearer ${GITHUB_TOKEN}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query: QUERY }),
  })

  if (!res.ok) {
    console.error(`GitHub API error: ${res.status} ${res.statusText}`)
    const body = await res.text()
    console.error(body)
    process.exit(1)
  }

  const json = await res.json()
  if (json.errors) {
    console.error('GraphQL errors:', JSON.stringify(json.errors, null, 2))
    process.exit(1)
  }

  const repos = json.data.viewer.repositories.nodes
  const withReadme = repos.filter((r) => r.object && r.object.text)
  console.log(`Found ${repos.length} repos, ${withReadme.length} have README`)

  const entries = withReadme.map(toProjectEntry)
  const content = `// Auto-generated by sync-pinned workflow. Do not edit manually.
import type { Project } from './projects';

export const projectsSynced: Project[] = [
${entries.join(',\n')}
];
`

  await writeFile(SYNCED_FILE, content)
  console.log(`Wrote ${entries.length} projects to src/data/projects-synced.ts`)
}

main()
